import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import ProfliePic from "../../public/images/profile/soul.png";
import SidePic from "../../public/images/svgs/side.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/icons';
import TransitionEffect from '@/components/TransitionEffect';


export default function Home() {
  return (
    <>
      <Head>
        <title>Halara Soul</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark min-h-screen dark:text-light'>
      <Layout className='pt-0 md:pt-16 sm:pt-8 '>
        <div className="flex items-center justify-between w-full lg:flex-col">
          <div className='w-1/2 md:w-full'>
            <Image src={ProfliePic} alt="Halara Soul" className='w-full h-auto lg:hidden md:inline-block md:w-full' 
            priority
            sizes="(max-width: 768px) 100vw,
            (ma-width: 1200px) 50vw,
            33vw"
            ></Image>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Halara Soul's Art Dome" className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl'></AnimatedText>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs '>Drawing has been a part of me since childhood, and now I realize its always been a true passion of mine. Welcome to my art dome! Im Halara Soul, a self-taught digital artist from the Philippines. I specialize in drawing women and fanart, but I also create original characters and more. As I continue to grow in my art journey, I hope youll join me and support my creative endeavors!</p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="mailto:halara.an@gmail.com" target={"_blank"} className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:border-light hover:dark:text-light md:p-2 md:px-4 md:text-base">
                  Hire Me
                  <LinkArrow className={"w-5 h-auto ml-1"} />
                  </Link>
                  <Link href="/projects" className="ml-4 flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:border-light hover:dark:text-light md:p-2 md:px-4 md:text-base">
                  My Art
                  <LinkArrow className={"w-5 h-auto ml-1"} />
                  </Link>
              </div>
            </div>
        </div>
      </Layout>
      <div className='absolute right-8 bottom-8 inline-block w-32 h-auto'>
        <Image src={SidePic} alt='Halara Soul' className='w-full h-auto md:hidden'></Image>
      </div>
      </main>
    </>
  )
}
